name: Workflow template
on:
  workflow_dispatch:
jobs:
  slackbuild_and_upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: ghcr.io/ich777/unraid_kernel:gcc_14.2.0
      options: --privileged -v /usr/local/lib/android:/host/android -v /usr/share/dotnet:/host/dotnet -v /opt/ghc:/host/ghc -v /opt/hostedtoolcache:/host/tools
    steps:
    -
      name: Free Disk Space (Manual)
      run: |
        echo "Freeing space by deleting mapped host directories..."
        # We mapped these to /host/... to avoid clashing with container paths
        rm -dr /host/android/* || true
        rm -dr /host/dotnet/* || true
        rm -dr /host/ghc/* || true
        rm -dr /host/tools/* || true
        echo "Disk space freed."
        df -h
    -
      # Bootstrap step – define env vars, aliases, functions once
      name: Bootstrap environment
      run: |
        # Environment variables (persist via $GITHUB_ENV)
        # echo "MYVAR=hello" >> $GITHUB_ENV
        # echo "FOO=bar" >> $GITHUB_ENV
        # Aliases & functions (persist via $BASH_ENV)
        cat >>"/etc/bootstrap" <<'EOF'
        
          gecho() { printf '\033[0;32m'; command echo "$@"; printf '\033[0m'; }
          alias wget='wget -q'
          slackpkginstall() {
          command slackpkg install "$@" <<< y 2>&1 | grep -E 'Installing package|GPG key added|Package .* installed\.'
        }
        EOF
    -
      name: Install dependencies
      run: |
        . /etc/bootstrap
        sed -i 's/^#*\s*BATCH=.*/BATCH=on/' /etc/slackpkg/slackpkg.conf
        sed -i 's/^#*\s*DEFAULT_ANSWER=.*/DEFAULT_ANSWER=y/' /etc/slackpkg/slackpkg.conf
        gecho "Installing needed packages..."
        slackpkg update gpg <<< y
        slackpkg remove squashfs-tools-4.5-x86_64-2 openssl-3.1.1-x86_64-1 aaa_glibc-solibs-2.37-x86_64-2 coreutils-9.3-x86_64-1 gawk-5.2.2-x86_64-1 gettext-0.22-x86_64-1 libseccomp-2.5.4-x86_64-1 ncurses-6.4_20230610-x86_64-1 util-linux-2.39.1-x86_64-3 xz-5.4.3-x86_64-1
        slackpkg install zlib nghttp3 pahole llvm libedit libxml2
        slackpkg upgrade glibc gcc
    - 
      name: Checkout
      uses: actions/checkout@v4
    - name: Cache packages
      id: cache-packages
      uses: actions/cache@v4
      with:
        path: /var/cache/packages
        key: slackware-packages-${{ github.sha }}
        restore-keys: |
          slackware-packages-
        # key: ${{ runner.os }}-slackpkg-${{ hashFiles('**/package-list.txt') }}
        # restore-keys: |
        #   ${{ runner.os }}-slackpkg-
        #key: slackpkg-${{ runner.os }}-${{ inputs.VERSION }}-${{ hashFiles('SlackBuilds/**/*') }}
        #restore-keys: |
        #  slackpkg-${{ runner.os }}-${{ inputs.VERSION }}-
    -
      name: Download unRaid
      run: |
        . /etc/bootstrap
        gecho "Finding latest unRaid version..."
        RESPONSE=$(curl -s https://releases.unraid.net/usb-creator)
        URL=$(echo $RESPONSE | jq -r '.os_list | max_by(.name | ltrimstr("Unraid ") | split(".") | map(tonumber)) | .url' | cut -d'?' -f1)
        NAME=$(echo $RESPONSE | jq -r '.os_list | max_by(.name | ltrimstr("Unraid ") | split(".") | map(tonumber)) | .name')
        FILENAME=$(basename "${URL}")
        VERSION_ID=$(echo $NAME | sed 's/^Unraid //')
        echo "VERSION_ID=$VERSION_ID" >> $GITHUB_ENV
        gecho "Downloading ${VERSION_ID}... "
        [ -f $FILENAME ] || wget $URL
        gecho "done."
        gecho "Extracting Unraid... "
        unzip -o -q $FILENAME -d unRAIDServer
        gecho "done."
    -
      name: Download Linux kernel
      run: |
        . /etc/bootstrap
        gecho "Determining kernel version needed for Unraid... "
        cd unRAIDServer    
        KERNEL_VERSION=$(file bzimage | awk -F'version ' '{print $2}' | cut -d' ' -f1 | cut -d'-' -f1)
        echo "KERNEL_VERSION=$KERNEL_VERSION" >> $GITHUB_ENV
        MAJOR_VERSION=${KERNEL_VERSION%%.*}
        gecho "Downloading Linux kernel ${KERNEL_VERSION}... "
        cd ..
        [ -f linux-${KERNEL_VERSION}.tar.xz ] || wget https://cdn.kernel.org/pub/linux/kernel/v${MAJOR_VERSION}.x/linux-${KERNEL_VERSION}.tar.xz
        gecho "done."
        gecho "Extracting Linux kernel... "
        mkdir -p linux
        tar xf linux-${KERNEL_VERSION}.tar.xz -C linux --strip-components 1
        gecho "done."
    -
      name: Patch kernel
      run: |
        . /etc/bootstrap
        gecho "Copying patches... "
        cd unRAIDServer
        unsquashfs -d patches bzmodules src
        cd ..
        cp -r unRAIDServer/patches/src/linux-*-Unraid/. linux/
        gecho "done."
        gecho "Applying patches... "
        cd linux
        find . -type f -iname '*.patch' -print0 | xargs -n1 -0 patch -p1 -i
        gecho "done."
        gecho "Applying kernel config... "
        make -j$(nproc) olddefconfig
        # SET THE NEW KERNEL NAME HERE
        ./scripts/config --set-str CONFIG_LOCALVERSION "-Unraid-eBPF"
        # FIX COMPRESSION ALGORITHMS TO MATCH UNRAID STOCK EXPECTATIONS
        ./scripts/config --disable CONFIG_KERNEL_GZIP \
            --enable CONFIG_KERNEL_LZMA
        ./scripts/config --enable CONFIG_MD_UNRAID \
            --enable CONFIG_DEBUG_INFO \
            --disable CONFIG_DEBUG_INFO_NONE \
            --enable CONFIG_DEBUG_INFO_DWARF5 \
            --disable CONFIG_DEBUG_INFO_REDUCED \
            --enable CONFIG_DEBUG_INFO_COMPRESSED_NONE \
            --disable CONFIG_DEBUG_INFO_COMPRESSED_ZLIB \
            --disable CONFIG_DEBUG_INFO_COMPRESSED_ZSTD \
            --disable CONFIG_DEBUG_INFO_SPLIT \
            --enable CONFIG_DEBUG_INFO_BTF \
            --enable CONFIG_PAHOLE_HAS_SPLIT_BTF \
            --enable CONFIG_PAHOLE_HAS_LANG_EXCLUDE \
            --enable CONFIG_DEBUG_INFO_BTF_MODULES \
            --disable CONFIG_MODULE_ALLOW_BTF_MISMATCH \
            --disable CONFIG_GDB_SCRIPTS \
            --enable CONFIG_PROBE_EVENTS_BTF_ARGS \
            --disable CONFIG_SCHED_CLASS_EXT \
            --enable CONFIG_IKCONFIG \
            --enable CONFIG_IKCONFIG_PROC \
            --enable CONFIG_KPROBES \
            --enable CONFIG_SECURITY \
            --enable CONFIG_SECURITY_PATH \
            --enable CONFIG_FTRACE_SYSCALLS \
            --enable CONFIG_BPF_LSM \
            --enable CONFIG_BPF_SYSCALL \
            --enable CONFIG_BPF_EVENTS \
            --enable CONFIG_SECURITYFS \
            --enable CONFIG_BPF_JIT
            make -j$(nproc) olddefconfig
            cp .config ../kernel.config
        gecho "done."
    -
      name: Build
      run: |
        . /etc/bootstrap
        gecho "Cleaning up before build... "
        rm -f linux-${KERNEL_VERSION}.tar.xz
        rm -f unRAIDServer-*.zip
        rm -rf unRAIDServer/patches
        df -h
        gecho "done."
        cd linux
        gecho "Making bzImage... "
        bzimagename=bzimage-${VERSION_ID}
        make -j$(nproc) bzImage > /dev/null
        mv arch/x86/boot/bzImage ../$bzimagename
        cd ..
        sha256sum $bzimagename > $bzimagename.sha256
        cd linux
        gecho "done."
        gecho "Making... "
        make -j$(nproc) > /dev/null
        gecho "done."
        
        gecho "Making modules... "
        make -j$(nproc) modules > /dev/null
        # make INSTALL_MOD_PATH=../modules INSTALL_MOD_STRIP=1 modules_install > /dev/null
        make INSTALL_MOD_PATH=../modules modules_install > /dev/null
        find ../modules -name '*.ko' -exec pahole --btf_encode {} \;
        cd ..
        # UPDATED TO -Unraid-eBPF
        depmod -b modules ${KERNEL_VERSION}-Unraid-eBPF
        gecho "done."
        gecho "Creating bzmodules... "
        cd unRAIDServer
        unsquashfs -d modules bzmodules
        cd ..
        # UPDATED TO -Unraid-eBPF
        rm -rf unRAIDServer/modules/lib/modules/*-Unraid-eBPF
        cp -r modules/lib/modules/${KERNEL_VERSION}-Unraid-eBPF unRAIDServer/modules/lib/modules
        cd unRAIDServer
        # ADDED -comp zstd TO MATCH STOCK UNRAID REQUIREMENTS
        mksquashfs modules ../bzmodules-${VERSION_ID} -comp zstd
        cd ..
        sha256sum bzmodules-${VERSION_ID} > bzmodules-${VERSION_ID}.sha256
        gecho "done."
        gecho "Extracting BTF... "
        cd linux
        cp vmlinux ../vmlinux
        cd ..
        llvm-objcopy --dump-section .BTF=vmlinux-${VERSION_ID}.btf vmlinux
        gecho "done."
        gecho "Cleaning up... "
        rm vmlinux
        rm -dr ./linux/
        rm -dr ./unRAIDServer/
        # rm unRAIDServer-*
        # rm -dr linux-*
        rm -dr ./modules/
        gecho "done."
    - 
      name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.VERSION_ID }}
        name: unRaid ${{ env.VERSION_ID }}
        body: |
          Build artifacts for unRaid ${{ env.VERSION_ID }}
          Kernel Version: ${{ env.KERNEL_VERSION }}
          
          **Files:**
          - `bzimage-${{ env.VERSION_ID }}` - Kernel image
          - `bzmodules-${{ env.VERSION_ID }}` - Kernel modules
          - `vmlinux-${{ env.VERSION_ID }}.btf` - BTF debug info
          - `kernel.config` - Kernel configuration
          - `.sha256` files for verification
        files: |
          bzimage-${{ env.VERSION_ID }}
          bzimage-${{ env.VERSION_ID }}.sha256
          bzmodules-${{ env.VERSION_ID }}
          bzmodules-${{ env.VERSION_ID }}.sha256
          vmlinux-${{ env.VERSION_ID }}.btf
          kernel.config
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
